export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SEARCH_ALL_PRODUCTS:"SEARCH_ALL_PRODUCTS",

    SET_ALL_PRODUCTS_BUTTON: "SET_ALL_PRODUCTS_BUTTON",
    SET_ID_BUTTON: "SET_ID_BUTTON",
    SET_CALCULATORS_BUTTON: "SET_CALCULATORS_BUTTON",
    SET_WATERBOTTLES_BUTTON: "SET_WATERBOTTLES_BUTTON",
    SET_ELECTRONICS_BUTTON:"SET_ELECTRONICS_BUTTON",
    SET_STATIONARY_BUTTON: "SET_STATIONARY_BUTTON",
    SET_OTHER_BUTTON: "SET_OTHER_BUTTON"

}